[2022-08-23 19:19:34,128] {processor.py:153} INFO - Started process (PID=1571) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:19:34,129] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:19:34,129] {logging_mixin.py:115} INFO - [2022-08-23 19:19:34,129] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:19:34,849] {logging_mixin.py:115} INFO - [2022-08-23 19:19:34,847] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:19:34,849] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:19:34,898] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.770 seconds
[2022-08-23 19:20:06,306] {processor.py:153} INFO - Started process (PID=1619) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:06,307] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:20:06,307] {logging_mixin.py:115} INFO - [2022-08-23 19:20:06,307] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:07,351] {logging_mixin.py:115} INFO - [2022-08-23 19:20:07,349] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:20:07,351] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:07,390] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.085 seconds
[2022-08-23 19:20:38,862] {processor.py:153} INFO - Started process (PID=1662) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:38,862] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:20:38,863] {logging_mixin.py:115} INFO - [2022-08-23 19:20:38,863] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:39,254] {logging_mixin.py:115} INFO - [2022-08-23 19:20:39,253] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:20:39,254] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:20:39,297] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.435 seconds
[2022-08-23 19:21:10,416] {processor.py:153} INFO - Started process (PID=1700) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:10,416] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:21:10,416] {logging_mixin.py:115} INFO - [2022-08-23 19:21:10,416] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:11,300] {logging_mixin.py:115} INFO - [2022-08-23 19:21:11,298] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:21:11,300] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:11,347] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.933 seconds
[2022-08-23 19:21:43,477] {processor.py:153} INFO - Started process (PID=1741) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:43,477] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:21:43,478] {logging_mixin.py:115} INFO - [2022-08-23 19:21:43,478] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:44,582] {logging_mixin.py:115} INFO - [2022-08-23 19:21:44,579] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:21:44,583] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:21:44,640] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.164 seconds
[2022-08-23 19:22:16,369] {processor.py:153} INFO - Started process (PID=1819) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:16,370] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:22:16,370] {logging_mixin.py:115} INFO - [2022-08-23 19:22:16,370] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:17,453] {logging_mixin.py:115} INFO - [2022-08-23 19:22:17,450] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:22:17,453] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:17,497] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.128 seconds
[2022-08-23 19:22:48,906] {processor.py:153} INFO - Started process (PID=1863) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:48,907] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:22:48,907] {logging_mixin.py:115} INFO - [2022-08-23 19:22:48,907] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:49,931] {logging_mixin.py:115} INFO - [2022-08-23 19:22:49,929] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:22:49,931] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:22:49,970] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.065 seconds
[2022-08-23 19:23:21,140] {processor.py:153} INFO - Started process (PID=1902) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:21,140] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:23:21,141] {logging_mixin.py:115} INFO - [2022-08-23 19:23:21,141] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:22,019] {logging_mixin.py:115} INFO - [2022-08-23 19:23:22,017] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:23:22,020] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:22,059] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.919 seconds
[2022-08-23 19:23:53,354] {processor.py:153} INFO - Started process (PID=1921) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:53,355] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:23:53,355] {logging_mixin.py:115} INFO - [2022-08-23 19:23:53,355] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:54,291] {logging_mixin.py:115} INFO - [2022-08-23 19:23:54,289] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:23:54,291] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:23:54,334] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.981 seconds
[2022-08-23 19:24:25,201] {processor.py:153} INFO - Started process (PID=1923) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:25,201] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:24:25,202] {logging_mixin.py:115} INFO - [2022-08-23 19:24:25,202] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:26,066] {logging_mixin.py:115} INFO - [2022-08-23 19:24:26,064] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:24:26,066] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:26,106] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.906 seconds
[2022-08-23 19:24:57,115] {processor.py:153} INFO - Started process (PID=1928) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:57,116] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:24:57,116] {logging_mixin.py:115} INFO - [2022-08-23 19:24:57,116] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:57,597] {logging_mixin.py:115} INFO - [2022-08-23 19:24:57,596] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:24:57,599] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:24:57,647] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.532 seconds
[2022-08-23 19:25:28,500] {processor.py:153} INFO - Started process (PID=1930) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:25:28,500] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:25:28,500] {logging_mixin.py:115} INFO - [2022-08-23 19:25:28,500] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:25:29,061] {logging_mixin.py:115} INFO - [2022-08-23 19:25:29,060] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:25:29,061] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:25:29,100] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.600 seconds
[2022-08-23 19:25:59,936] {processor.py:153} INFO - Started process (PID=1935) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:25:59,936] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:25:59,936] {logging_mixin.py:115} INFO - [2022-08-23 19:25:59,936] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:26:00,455] {logging_mixin.py:115} INFO - [2022-08-23 19:26:00,453] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:26:00,455] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:26:00,492] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.557 seconds
[2022-08-23 19:26:31,282] {processor.py:153} INFO - Started process (PID=1937) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:26:31,282] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:26:31,282] {logging_mixin.py:115} INFO - [2022-08-23 19:26:31,282] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:26:31,672] {logging_mixin.py:115} INFO - [2022-08-23 19:26:31,672] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:26:31,672] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:26:31,715] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.434 seconds
[2022-08-23 19:27:02,514] {processor.py:153} INFO - Started process (PID=1939) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:02,514] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:27:02,514] {logging_mixin.py:115} INFO - [2022-08-23 19:27:02,514] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:02,902] {logging_mixin.py:115} INFO - [2022-08-23 19:27:02,902] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:27:02,902] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:02,944] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.431 seconds
[2022-08-23 19:27:33,742] {processor.py:153} INFO - Started process (PID=1958) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:33,742] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:27:33,742] {logging_mixin.py:115} INFO - [2022-08-23 19:27:33,742] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:34,137] {logging_mixin.py:115} INFO - [2022-08-23 19:27:34,136] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:27:34,137] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:27:34,180] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.439 seconds
[2022-08-23 19:28:04,983] {processor.py:153} INFO - Started process (PID=1996) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:04,983] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:28:04,984] {logging_mixin.py:115} INFO - [2022-08-23 19:28:04,984] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:05,379] {logging_mixin.py:115} INFO - [2022-08-23 19:28:05,379] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 34, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:28:05,379] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:05,422] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.439 seconds
[2022-08-23 19:28:36,302] {processor.py:153} INFO - Started process (PID=2034) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:36,302] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:28:36,302] {logging_mixin.py:115} INFO - [2022-08-23 19:28:36,302] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:36,691] {logging_mixin.py:115} INFO - [2022-08-23 19:28:36,691] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:28:36,692] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:28:36,740] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.439 seconds
[2022-08-23 19:29:07,529] {processor.py:153} INFO - Started process (PID=2073) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:07,529] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:29:07,529] {logging_mixin.py:115} INFO - [2022-08-23 19:29:07,529] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:07,920] {logging_mixin.py:115} INFO - [2022-08-23 19:29:07,919] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:29:07,920] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:07,962] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.434 seconds
[2022-08-23 19:29:38,798] {processor.py:153} INFO - Started process (PID=2112) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:38,798] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:29:38,798] {logging_mixin.py:115} INFO - [2022-08-23 19:29:38,798] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:39,186] {logging_mixin.py:115} INFO - [2022-08-23 19:29:39,185] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:29:39,186] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:29:39,228] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.431 seconds
[2022-08-23 19:30:10,019] {processor.py:153} INFO - Started process (PID=2153) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:10,019] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:30:10,020] {logging_mixin.py:115} INFO - [2022-08-23 19:30:10,020] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:10,418] {logging_mixin.py:115} INFO - [2022-08-23 19:30:10,418] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:30:10,418] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:10,462] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.443 seconds
[2022-08-23 19:30:41,259] {processor.py:153} INFO - Started process (PID=2190) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:41,259] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:30:41,260] {logging_mixin.py:115} INFO - [2022-08-23 19:30:41,260] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:41,651] {logging_mixin.py:115} INFO - [2022-08-23 19:30:41,650] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:30:41,651] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:30:41,694] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.435 seconds
[2022-08-23 19:31:12,499] {processor.py:153} INFO - Started process (PID=2233) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:12,499] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:31:12,499] {logging_mixin.py:115} INFO - [2022-08-23 19:31:12,499] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:12,892] {logging_mixin.py:115} INFO - [2022-08-23 19:31:12,891] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:31:12,892] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:12,935] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.436 seconds
[2022-08-23 19:31:43,741] {processor.py:153} INFO - Started process (PID=2270) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:43,741] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:31:43,742] {logging_mixin.py:115} INFO - [2022-08-23 19:31:43,742] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:44,131] {logging_mixin.py:115} INFO - [2022-08-23 19:31:44,130] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:31:44,131] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:31:44,174] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.433 seconds
[2022-08-23 19:32:14,986] {processor.py:153} INFO - Started process (PID=2307) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:14,986] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:32:14,986] {logging_mixin.py:115} INFO - [2022-08-23 19:32:14,986] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:15,398] {logging_mixin.py:115} INFO - [2022-08-23 19:32:15,398] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:32:15,398] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:15,441] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.456 seconds
[2022-08-23 19:32:46,237] {processor.py:153} INFO - Started process (PID=2344) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:46,237] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:32:46,237] {logging_mixin.py:115} INFO - [2022-08-23 19:32:46,237] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:46,639] {logging_mixin.py:115} INFO - [2022-08-23 19:32:46,639] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:32:46,639] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:32:46,682] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.445 seconds
[2022-08-23 19:33:17,481] {processor.py:153} INFO - Started process (PID=2382) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:17,481] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:33:17,481] {logging_mixin.py:115} INFO - [2022-08-23 19:33:17,481] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:17,873] {logging_mixin.py:115} INFO - [2022-08-23 19:33:17,872] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:33:17,873] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:17,915] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.435 seconds
[2022-08-23 19:33:48,785] {processor.py:153} INFO - Started process (PID=2422) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:48,785] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:33:48,785] {logging_mixin.py:115} INFO - [2022-08-23 19:33:48,785] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:49,249] {logging_mixin.py:115} INFO - [2022-08-23 19:33:49,248] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:33:49,249] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:33:49,288] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.504 seconds
[2022-08-23 19:42:32,278] {processor.py:153} INFO - Started process (PID=2429) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:42:32,278] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:42:32,278] {logging_mixin.py:115} INFO - [2022-08-23 19:42:32,278] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:42:34,256] {logging_mixin.py:115} INFO - [2022-08-23 19:42:34,255] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:42:34,256] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:42:34,396] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 2.119 seconds
[2022-08-23 19:43:06,262] {processor.py:153} INFO - Started process (PID=2501) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:06,262] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:43:06,263] {logging_mixin.py:115} INFO - [2022-08-23 19:43:06,263] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:07,406] {logging_mixin.py:115} INFO - [2022-08-23 19:43:07,404] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:43:07,407] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:07,446] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.185 seconds
[2022-08-23 19:43:38,304] {processor.py:153} INFO - Started process (PID=2541) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:38,305] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:43:38,305] {logging_mixin.py:115} INFO - [2022-08-23 19:43:38,305] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:38,711] {logging_mixin.py:115} INFO - [2022-08-23 19:43:38,710] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:43:38,711] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:43:38,750] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.446 seconds
[2022-08-23 19:44:09,576] {processor.py:153} INFO - Started process (PID=2578) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:09,576] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:44:09,576] {logging_mixin.py:115} INFO - [2022-08-23 19:44:09,576] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:09,970] {logging_mixin.py:115} INFO - [2022-08-23 19:44:09,970] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:44:09,971] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:10,015] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.440 seconds
[2022-08-23 19:44:40,826] {processor.py:153} INFO - Started process (PID=2618) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:40,826] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:44:40,826] {logging_mixin.py:115} INFO - [2022-08-23 19:44:40,826] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:41,216] {logging_mixin.py:115} INFO - [2022-08-23 19:44:41,215] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:44:41,216] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:44:41,259] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.434 seconds
[2022-08-23 19:45:12,059] {processor.py:153} INFO - Started process (PID=2656) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:12,059] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:45:12,060] {logging_mixin.py:115} INFO - [2022-08-23 19:45:12,060] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:12,450] {logging_mixin.py:115} INFO - [2022-08-23 19:45:12,449] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:45:12,450] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:12,492] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.433 seconds
[2022-08-23 19:45:43,296] {processor.py:153} INFO - Started process (PID=2694) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:43,296] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:45:43,297] {logging_mixin.py:115} INFO - [2022-08-23 19:45:43,297] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:43,687] {logging_mixin.py:115} INFO - [2022-08-23 19:45:43,687] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:45:43,688] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:45:43,729] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.433 seconds
[2022-08-23 19:46:14,529] {processor.py:153} INFO - Started process (PID=2731) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:14,529] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:46:14,529] {logging_mixin.py:115} INFO - [2022-08-23 19:46:14,529] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:14,925] {logging_mixin.py:115} INFO - [2022-08-23 19:46:14,924] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:46:14,925] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:14,967] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.439 seconds
[2022-08-23 19:46:45,775] {processor.py:153} INFO - Started process (PID=2772) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:45,775] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:46:45,775] {logging_mixin.py:115} INFO - [2022-08-23 19:46:45,775] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:46,168] {logging_mixin.py:115} INFO - [2022-08-23 19:46:46,168] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:46:46,168] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:46:46,208] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.434 seconds
[2022-08-23 19:47:17,174] {processor.py:153} INFO - Started process (PID=2819) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:17,174] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:47:17,175] {logging_mixin.py:115} INFO - [2022-08-23 19:47:17,175] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:18,181] {logging_mixin.py:115} INFO - [2022-08-23 19:47:18,179] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:47:18,182] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:18,219] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.046 seconds
[2022-08-23 19:47:49,068] {processor.py:153} INFO - Started process (PID=2871) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:49,068] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:47:49,068] {logging_mixin.py:115} INFO - [2022-08-23 19:47:49,068] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:49,885] {logging_mixin.py:115} INFO - [2022-08-23 19:47:49,883] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:47:49,886] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:47:49,929] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.862 seconds
[2022-08-23 19:48:20,769] {processor.py:153} INFO - Started process (PID=2910) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:20,769] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:48:20,769] {logging_mixin.py:115} INFO - [2022-08-23 19:48:20,769] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:21,162] {logging_mixin.py:115} INFO - [2022-08-23 19:48:21,161] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:48:21,162] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:21,209] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.441 seconds
[2022-08-23 19:48:51,992] {processor.py:153} INFO - Started process (PID=2948) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:51,992] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:48:51,992] {logging_mixin.py:115} INFO - [2022-08-23 19:48:51,992] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:52,389] {logging_mixin.py:115} INFO - [2022-08-23 19:48:52,388] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:48:52,389] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:48:52,432] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.440 seconds
[2022-08-23 19:49:23,240] {processor.py:153} INFO - Started process (PID=2986) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:23,240] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:49:23,240] {logging_mixin.py:115} INFO - [2022-08-23 19:49:23,240] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:23,633] {logging_mixin.py:115} INFO - [2022-08-23 19:49:23,633] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:49:23,634] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:23,682] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.443 seconds
[2022-08-23 19:49:54,455] {processor.py:153} INFO - Started process (PID=3026) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:54,455] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:49:54,455] {logging_mixin.py:115} INFO - [2022-08-23 19:49:54,455] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:54,852] {logging_mixin.py:115} INFO - [2022-08-23 19:49:54,852] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:49:54,852] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:49:54,895] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.441 seconds
[2022-08-23 19:50:25,706] {processor.py:153} INFO - Started process (PID=3065) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:50:25,706] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:50:25,706] {logging_mixin.py:115} INFO - [2022-08-23 19:50:25,706] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:50:26,101] {logging_mixin.py:115} INFO - [2022-08-23 19:50:26,101] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:50:26,102] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:50:26,144] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.439 seconds
[2022-08-23 19:58:25,724] {processor.py:153} INFO - Started process (PID=3097) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:58:25,724] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:58:25,724] {logging_mixin.py:115} INFO - [2022-08-23 19:58:25,724] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:58:27,567] {logging_mixin.py:115} INFO - [2022-08-23 19:58:27,567] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:58:27,568] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:58:27,810] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 2.086 seconds
[2022-08-23 19:58:59,685] {processor.py:153} INFO - Started process (PID=3165) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:58:59,685] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:58:59,686] {logging_mixin.py:115} INFO - [2022-08-23 19:58:59,685] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:59:00,231] {logging_mixin.py:115} INFO - [2022-08-23 19:59:00,229] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:59:00,231] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:59:00,271] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 0.587 seconds
[2022-08-23 19:59:31,743] {processor.py:153} INFO - Started process (PID=3207) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:59:31,744] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-23 19:59:31,744] {logging_mixin.py:115} INFO - [2022-08-23 19:59:31,744] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:59:32,863] {logging_mixin.py:115} INFO - [2022-08-23 19:59:32,860] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 31, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-23 19:59:32,863] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-23 19:59:32,910] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.168 seconds
