[2022-08-23 21:35:57,754] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipeline.gmailAuthTask manual__2022-08-24T01:35:55.237738+00:00 [queued]>
[2022-08-23 21:35:57,759] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: gmailPipeline.gmailAuthTask manual__2022-08-24T01:35:55.237738+00:00 [queued]>
[2022-08-23 21:35:57,759] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 21:35:57,759] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 21:35:57,759] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 21:35:57,768] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): gmailAuthTask> on 2022-08-24 01:35:55.237738+00:00
[2022-08-23 21:35:57,771] {standard_task_runner.py:52} INFO - Started process 8673 to run task
[2022-08-23 21:35:57,777] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'gmailPipeline', 'gmailAuthTask', 'manual__2022-08-24T01:35:55.237738+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/gmailDag.py', '--cfg-path', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmp899d2mt7', '--error-file', '/var/folders/mm/xv24gcjj46l_jx1m76p5bgy80000gn/T/tmphiqu7tzc']
[2022-08-23 21:35:57,779] {standard_task_runner.py:80} INFO - Job 16: Subtask gmailAuthTask
[2022-08-23 21:35:57,826] {task_command.py:371} INFO - Running <TaskInstance: gmailPipeline.gmailAuthTask manual__2022-08-24T01:35:55.237738+00:00 [running]> on host abhays-mbp.lan
[2022-08-23 21:35:57,872] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=gmailPipeline
AIRFLOW_CTX_TASK_ID=gmailAuthTask
AIRFLOW_CTX_EXECUTION_DATE=2022-08-24T01:35:55.237738+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-24T01:35:55.237738+00:00
[2022-08-23 21:35:57,913] {python.py:173} INFO - Done. Returned value was: [<google.oauth2.credentials.Credentials object at 0x11e3993a0>, Engine(mysql+pymysql://root:***@localhost/gmailTables)]
[2022-08-23 21:35:57,916] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config.
[2022-08-23 21:35:57,916] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2405, in xcom_push
    XCom.set(
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 192, in set
    value = cls.serialize_value(
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/Users/abhaymone/.pyenv/versions/3.9.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/abhaymone/.pyenv/versions/3.9.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/abhaymone/.pyenv/versions/3.9.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/abhaymone/.pyenv/versions/3.9.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Credentials is not JSON serializable
[2022-08-23 21:35:57,932] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=gmailPipeline, task_id=gmailAuthTask, execution_date=20220824T013555, start_date=20220824T013557, end_date=20220824T013557
[2022-08-23 21:35:57,943] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task gmailAuthTask (Object of type Credentials is not JSON serializable; 8673)
[2022-08-23 21:35:57,951] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-23 21:35:57,978] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
