[2022-08-21 21:48:07,022] {processor.py:153} INFO - Started process (PID=9944) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 21:48:07,023] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-21 21:48:07,023] {logging_mixin.py:115} INFO - [2022-08-21 21:48:07,023] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 21:48:09,342] {logging_mixin.py:115} INFO - [2022-08-21 21:48:09,337] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-21 21:48:09,342] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 21:48:09,494] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 2.473 seconds
[2022-08-21 22:40:51,586] {processor.py:153} INFO - Started process (PID=9967) to work on /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 22:40:51,587] {processor.py:641} INFO - Processing file /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py for tasks to queue
[2022-08-21 22:40:51,587] {logging_mixin.py:115} INFO - [2022-08-21 22:40:51,587] {dagbag.py:508} INFO - Filling up the DagBag from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 22:40:53,373] {logging_mixin.py:115} INFO - [2022-08-21 22:40:53,371] {dagbag.py:321} ERROR - Failed to import: /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
Traceback (most recent call last):
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py", line 28, in <module>
    python_callable=task1,
NameError: name 'task1' is not defined
[2022-08-21 22:40:53,373] {processor.py:653} WARNING - No viable dags retrieved from /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py
[2022-08-21 22:40:53,547] {processor.py:161} INFO - Processing /Users/abhaymone/src/dev/sand/MANAGE-GMAIL/dags/gmailDag.py took 1.961 seconds
